class AppConstants {
  static const String tokenKey = 'diasense_access_token';
  static const String refreshTokenKey = 'diasense_refresh_token';
  static const String userIdKey = 'diasense_user_id';
  static const String userEmailKey = 'diasense_user_email';
  static const String userNameKey = 'diasense_user_name';
  static const String hasSeenOnboardingKey = 'diasense_has_seen_onboarding';
  static const String themeModeKey = 'diasense_theme_mode';
  
  // Disclaimer
  static const String medicalDisclaimer = 
      'DiaSense AI is an assistive risk assessment and lifestyle tracking tool. '
      'Results generated by machine learning models do not constitute a clinical medical diagnosis. '
      'Always seek guidance from a qualified physician for clinical care and diagnostic confirmation.';
}
